name: Daily Scheduled Task

on:
  schedule:
    - cron: '*/10 * * *'  # Runs daily at 12:00 UTC

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Run Python script
        run: |
          echo "Running daily task!"
          echo "Current date and time : $current_date_time"
          # Your Python code or script execution here
          python -c "print('Hello, GitHub Actions!')"
