name: Run Python Script Daily

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # If you have dependencies

      - name: Run Python script
        run: pf2.py  # Replace 'script.py' with your filename
