name: Daily Scheduled Task

on:
  schedule:
    - cron: '20 9 * * 1'  # Runs daily at 8:00 UTC

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Run Python script
        run: |
          echo "Running daily task!"
          # Your Python code or script execution here
          # Example: python -c "print('Hello, GitHub Actions!')"
