name: Scheduled Python Script with folder

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every hour (you can adjust this)

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        run: |
          pf21.py

      - name: Commit Output Files
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add output/
          git commit -m "Add output files"
          git push
